TASKS = {
    "service_restart": {
        "id": "service_restart",
        "name": "Easy: API Process Crash",
        "difficulty": "easy",
        "max_steps": 5,
        "noise_level": 0.0,
        "required_sequence": ["restart_service"],
        "flakiness_range": (0.10, 0.12),
        "nominal_metrics": {
            "error_rate": 0.02,
            "latency": 0.06,
            "cpu_load": 0.18,
            "memory_usage": 0.26,
        },
        "initial_state": {
            "services": {
                "auth-api": "DOWN",
                "main-db": "RUNNING",
                "cache": "RUNNING",
            },
            "metrics": {
                "cpu_load": 0.22,
                "memory_usage": 0.33,
                "latency": 0.78,
                "error_rate": 0.91,
            },
            "state": {
                "internal_error_rate": 0.91,
                "is_database_locked": False,
                "active_incidents": ["auth_api_process_crash"],
                "leak_active": False,
                "db_pool_exhausted": False,
                "db_scaled": False,
                "connections_cleared": False,
            },
            "logs": [
                "System initialized. All services green except active incident targets.",
                "[ERROR] auth-api exited with code 137",
                "[ERROR] supervisor: auth-api process not running",
                "[HINT] Client traffic is failing because auth-api is DOWN",
            ],
        },
    },
    "memory_leak": {
        "id": "memory_leak",
        "name": "Medium: Worker Memory Leak",
        "difficulty": "medium",
        "max_steps": 10,
        "noise_level": 0.5,
        "required_sequence": ["kill_process", "restart_service"],
        "flakiness_range": (0.12, 0.16),
        "nominal_metrics": {
            "error_rate": 0.03,
            "latency": 0.08,
            "cpu_load": 0.24,
            "memory_usage": 0.38,
        },
        "initial_state": {
            "services": {
                "auth-api": "DEGRADED",
                "main-db": "RUNNING",
                "cache": "RUNNING",
            },
            "metrics": {
                "cpu_load": 0.64,
                "memory_usage": 0.97,
                "latency": 0.83,
                "error_rate": 0.42,
            },
            "state": {
                "internal_error_rate": 0.42,
                "is_database_locked": False,
                "active_incidents": ["worker_memory_leak"],
                "leak_active": True,
                "db_pool_exhausted": False,
                "db_scaled": False,
                "connections_cleared": False,
            },
            "logs": [
                "System initialized. Triage the active incident.",
                "[WARN] worker-process memory usage climbed above 95%",
                "[ERROR] kernel: OOMKilled candidate detected for worker-process",
                "[ERROR] auth-api requests timing out while worker queue backs up",
            ],
        },
    },
    "db_connection_exhaustion": {
        "id": "db_connection_exhaustion",
        "name": "Hard: Distributed DB Pool Failure",
        "difficulty": "hard",
        "max_steps": 15,
        "noise_level": 0.8,
        "required_sequence": ["scale_db", "clear_connections"],
        "flakiness_range": (0.15, 0.20),
        "nominal_metrics": {
            "error_rate": 0.02,
            "latency": 0.09,
            "cpu_load": 0.29,
            "memory_usage": 0.41,
        },
        "initial_state": {
            "services": {
                "auth-api": "RUNNING",
                "main-db": "DEGRADED",
                "cache": "RUNNING",
            },
            "metrics": {
                "cpu_load": 0.46,
                "memory_usage": 0.58,
                "latency": 0.97,
                "error_rate": 0.37,
            },
            "state": {
                "internal_error_rate": 0.37,
                "is_database_locked": True,
                "active_incidents": ["db_connection_pool_exhaustion"],
                "leak_active": False,
                "db_pool_exhausted": True,
                "db_scaled": False,
                "connections_cleared": False,
            },
            "logs": [
                "System initialized. Triage the active incident.",
                "[INFO] auth-api pod health checks passing",
                "[INFO] main-db replication lag within normal range",
                "[WARN] Request latency elevated above SLO without explicit application errors",
            ],
        },
    },
}
